### PR TITLE
sandbox for working group proposals

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

Initial organization of MicroProfile Working Group proposals.

### CODE REVIEW

**Comment by kwsutter** [comment]
> Cloud Native for Java Working Group Proposal

Will do.

**Comment by starksm64** [comment]
The two proposals need to be clearly delineated in terms of who is backing them. Right now CN4J is an Eclipse Foundation proposal. The MPWG is an IBM, Red Hat and Tomitribe proposal. There are statements in the CN4J that look to be statements of fact that from one side that I would not want attributed to Red Hat for example.

**Comment by kwsutter** [comment]
> I would suggest a lead in to each proposal from the parent that identifies who is backing the proposal at this point in time. I can create an update after the MP call today.

Does it matter?  I mean why immediately tell the users which one is backed by whom?  Let each person read and weigh the pros and cons and let them come to their own conclusion.

**Comment by dblevins** [comment]
I say we either a) merge this as-is or b) use this as a place to talk about the Working Groups.

b) doesn't really enable people to submit their own proposal, so I might suggest a.

**Comment by kwsutter** [comment]
I'm going to go ahead with the merge.  We can update it via additional PRs as required.

**Comment by kwsutter** [comment]
> I would suggest a lead in to each proposal from the parent that identifies who is backing the proposal at this point in time. I can create an update after the MP call today.

Scott, can we go with what we have?  And, possibly update it with ownership information via another PR?  Thanks!  I need your approval before I can merge...  Thanks!

**Comment by starksm64** [comment]
> > I would suggest a lead in to each proposal from the parent that identifies who is backing the proposal at this point in time. I can create an update after the MP call today.
> 
> Scott, can we go with what we have? And, possibly update it with ownership information via another PR? Thanks! I need your approval before I can merge... Thanks!

Yes, that is fine.

**Comment by mmilinkov** [comment]
> 
> 
> The two proposals need to be clearly delineated in terms of who is backing them. Right now CN4J is an Eclipse Foundation proposal. The MPWG is an IBM, Red Hat and Tomitribe proposal. There are statements in the CN4J that look to be statements of fact that from one side that I would not want attributed to Red Hat for example.

The Eclipse Foundation does not operate in a vacuum and the CN4J proposal has been reviewed and vetted by a number of member companies. Nor do I believe that the MPWG proposal is necessarily the corporate position of either Red Hat or IBM. I do have confidence that David can speak on behalf of Tomitribe :)

**Comment by kwsutter** [comment]
> > The two proposals need to be clearly delineated in terms of who is backing them. Right now CN4J is an Eclipse Foundation proposal. The MPWG is an IBM, Red Hat and Tomitribe proposal. There are statements in the CN4J that look to be statements of fact that from one side that I would not want attributed to Red Hat for example.
> 
> The Eclipse Foundation does not operate in a vacuum and the CN4J proposal has been reviewed and vetted by a number of member companies. Nor do I believe that the MPWG proposal is necessarily the corporate position of either Red Hat or IBM. I do have confidence that David can speak on behalf of Tomitribe :)

Agree, Mike.  That's why I didn't want to assign "ownership" to the proposals.  There are pros and cons of each proposal that each organization needs to weigh.  And, although we have been talking with our respective organizations, I'm not speaking for all of IBM, nor could John or Scott speak for all of Red Hat.

**Pull request merged**
