### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mmusgrov**
This PR is a proposal for supporting "Consistency Models for Microservices". The actual proposal is:
https://github.com/eclipse/microprofile-sandbox/pull/2/files#diff-eeb2668147f799967ab5923f47f739a3

The TCK uses Arquilian to start up the two microservices (the LRA coordinator and test service) and is in our project repo: https://github.com/jbosstm/narayana/tree/master/rts/lra/lra-test

### CODE REVIEW

**Comment by mmusgrov** [comment]
@mikecroft I have asked each committer to sign the ECA.
As to the "Signed-Off-By (git commit -s)" failure:
- would it be acceptable for me to provide a single commit using the -S flag and then ensure that all future commits are signed;
- or do you need me to collapse all the commits and sign that single commit;
- or do you have a recommendation.

**Comment by mikecroft** [comment]
@mmusgrov this could be tricky. I believe everyone in the list will need to amend at least the latest commit (AFAIK - it may need to be every commit from them).

The added complication is that somewhere someone has used GitHub to commit a change so the `noreply@github.com` email is being picked up. There is [an open Bugzilla ticket to address that](https://bugs.eclipse.org/bugs/show_bug.cgi?id=521596), but other than it being accepted as a bug of the process there is no word on when that will be resolved.

In case the validator does need every commit to be signed, I'm sure you could squash *your own* commits without any issue, but I don't think other people's contributions could be since it would probably run in to trouble when doing the next IP review.

**Comment by mikecroft** [comment]
It's not 100% clear, but this document does suggest that every commit needs to be signed off:
https://wiki.eclipse.org/Development_Resources/Contributing_via_Git

It's literally just a string in the commit message, so if you could find a nice way with some Git tool to edit those manually, I'm sure that would work.

**Comment by mikecroft** [comment]
Since all IP checks have passed, I'll merge this based on "Step 0" in the process outlining this as a "merge first, fix later" repository.
https://wiki.eclipse.org/MicroProfile/FeatureInit

It looks like [John requested a change](https://groups.google.com/d/msg/microprofile/CJirjFkM9Do/ZRdWjJvmCQAJ), but this should be made in further PRs

> Ideally all source files would have a common license header.  https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/license-alv2.asciidoc can be used as an example.

**Comment by mmusgrov** [comment]
Thanks. I will be separately address issues as they come up in new PRs.

**Pull request merged**
